pipeline {
  agent none
  options { 
    buildDiscarder(logRotator(numToKeepStr: '2'))
    skipDefaultCheckout true
    preserveStashes(buildCount: 2)
  }
  environment {
    repoOwner = "${repoOwner}"
  }
  stages('Shell Test & Build') {
    stage('Tests') {
      agent any
      steps {
        sh '''
          echo Hello World!
        '''
      } 
    }
  }
}
